server:
  port: 8081
spring:
  application:
    name: gateway-limiter
  redis:
    host: localhost
    port: 6379
    database: 10
  output:
    ansi:
      enabled: always
eureka:
  client:
    serviceUrl:
      # 注册中心地址
      defaultZone: http://127.0.0.1:8762/eureka/

---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sys?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&useAffectedRows=true&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: root
    # 连接池最大连接数（使用负值表示没有限制）
    max-active: 20
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-wait: 1
    # 连接池中的最大空闲连接
    max-idle: 0
    # 连接池中的最小空闲连接
    min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 1000

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.love.*.mapper


# oauth2.0配置
client:
  oauth2:
    # 客户端标识Id
    client-id: appId
    # 客户端安全码
    secret: 123456
    # 授权类型
    grant_types:
      - password
      - refresh_token
    # token 有效期
    token-validity-time: 3600
    refresh-token-validity-time: 3600
    # 客户端访问范围
    scopes:
      - api
      - all
