server:
  port: 8081
spring:
  application:
    name: gateway-limiter
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
            #微服务名称大写转小写，因此下面lb://可以用小写描述服务名
          lower-case-service-id: true
      routes:
        - id: client-1
          uri: lb://client-1
          predicates:
          - Path=/exhibit/**
#          filters:
#          - StripPrefix=1
#          - name: RequestRateLimiter
#            args:
#              # 令牌桶算法每秒补充的token数量（每秒的请求数量）
#              redis-rate-limiter.replenishRate: 1
#              # 令牌桶算法token最大数量（每秒的最大请求数量）
#              redis-rate-limiter.burstCapacity: 2
#              key-resolver: "#{@apiKeyResolver}"
        - id: client-1
          uri: lb://client-2
          predicates:
          - Path=/foo2/**
  output:
    ansi:
      enabled: always
eureka:
  client:
    serviceUrl:
      # 注册中心地址
      defaultZone: http://127.0.0.1:8762/eureka/

---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboottest?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123
  redis:
    database: 10
    host: 127.0.0.1
    port: 6379
    password: 123
    timeout: 5000
    ssl: false
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0



