server:
  port: 8764

spring:
  application:
    name: eureka-server-3

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/,http://localhost:8763/eureka/
  server:
    use-read-only-response-cache: false
logging:
  level:
    root: warn