server:
  port: 8762

spring:
  application:
    name: eureka-server-1
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://localhost:8763/eureka/,http://localhost:8764/eureka/
  server:
    use-read-only-response-cache: false
logging:
  level:
    root: warn